"""YAML load/save helpers for `settings.yaml` and `sensors_enabled.yaml`.

Two-file model (PLAN.md decision (a)+(c)):

- `settings.yaml` -- user-owned. MQTT credentials, `device_name`, `client_id`,
  `update_interval`, `timezone`, optional `tls`, `ha_status_topic`. The
  installer writes this only on first install and never touches it on re-run.
- `sensors_enabled.yaml` -- generated by the installer. Holds the per-sensor
  list with `enabled` / `available` flags. The merge logic touches only this
  file.
"""

from __future__ import annotations

import os
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

import yaml


SETTINGS_FILENAME = "settings.yaml"
SENSORS_ENABLED_FILENAME = "sensors_enabled.yaml"

SENSORS_ENABLED_SCHEMA_VERSION = 1


class ConfigError(Exception):
    """Raised when a YAML file fails schema validation."""


@dataclass
class Settings:
    """User-owned runtime settings parsed from `settings.yaml`."""

    mqtt_hostname: str
    mqtt_port: int = 1883
    mqtt_username: str | None = None
    mqtt_password: str | None = None
    client_id: str = ""
    timezone: str = ""
    update_interval: int = 60
    ha_status_topic: str = "hass"
    device_name: str = ""
    tls_ca_certs: str | None = None
    tls_certfile: str | None = None
    tls_keyfile: str | None = None
    external_drives: dict[str, str] = field(default_factory=dict)


@dataclass
class SensorEntry:
    """One sensor's enable/available state in `sensors_enabled.yaml`."""

    enabled: bool
    available: bool


@dataclass
class SensorsEnabled:
    """Generated runtime sensor list parsed from `sensors_enabled.yaml`."""

    sensors: dict[str, SensorEntry] = field(default_factory=dict)
    last_probe_utc: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc)
    )


def settings_path(config_dir: Path) -> Path:
    """Return the absolute path to `settings.yaml` inside `config_dir`."""
    return config_dir / SETTINGS_FILENAME


def sensors_enabled_path(config_dir: Path) -> Path:
    """Return the absolute path to `sensors_enabled.yaml` inside `config_dir`."""
    return config_dir / SENSORS_ENABLED_FILENAME


def _atomic_write_text(path: Path, body: str) -> None:
    """Write `body` to `path` via a temp file + os.replace."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(body, encoding="utf-8")
    os.replace(tmp, path)


def _ensure_non_empty_str(value: Any, field_name: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ConfigError(f"{field_name} must be a non-empty string")
    return value


def _validate_timezone(tz: str) -> str:
    try:
        ZoneInfo(tz)
    except (ZoneInfoNotFoundError, ValueError) as exc:
        raise ConfigError(f"Invalid IANA timezone {tz!r}: {exc}") from exc
    return tz


def _validate_port(port: Any) -> int:
    if not isinstance(port, int) or isinstance(port, bool):
        raise ConfigError(f"mqtt.port must be an integer (got {port!r})")
    if port < 1 or port > 65535:
        raise ConfigError(f"mqtt.port must be between 1 and 65535 (got {port})")
    return port


def _coerce_optional_str(value: Any, field_name: str) -> str | None:
    if value is None:
        return None
    if not isinstance(value, str):
        raise ConfigError(f"{field_name} must be a string or null")
    return value


def load_settings(path: Path) -> Settings | None:
    """Return None if file doesn't exist. Raise ConfigError on schema violations."""
    if not path.exists():
        return None
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ConfigError(f"Could not parse {path}: {exc}") from exc
    if raw is None:
        raise ConfigError(f"{path} is empty")
    if not isinstance(raw, dict):
        raise ConfigError(f"{path} top-level must be a mapping")

    mqtt = raw.get("mqtt") or {}
    if not isinstance(mqtt, dict):
        raise ConfigError("'mqtt' must be a mapping")

    hostname = _ensure_non_empty_str(mqtt.get("hostname"), "mqtt.hostname")
    port = _validate_port(mqtt.get("port", 1883))
    username = _coerce_optional_str(mqtt.get("username"), "mqtt.username")
    password = _coerce_optional_str(mqtt.get("password"), "mqtt.password")

    client_id = _ensure_non_empty_str(raw.get("client_id"), "client_id")
    tz = _validate_timezone(_ensure_non_empty_str(raw.get("timezone"), "timezone"))

    update_interval = raw.get("update_interval", 60)
    if not isinstance(update_interval, int) or isinstance(update_interval, bool):
        raise ConfigError("update_interval must be an integer")
    if update_interval <= 0:
        raise ConfigError("update_interval must be positive")

    ha_status_topic = raw.get("ha_status_topic", "hass")
    if not isinstance(ha_status_topic, str) or not ha_status_topic:
        raise ConfigError("ha_status_topic must be a non-empty string")

    device_name_raw = _ensure_non_empty_str(raw.get("device_name"), "device_name")
    device_name = device_name_raw.lower()

    tls = raw.get("tls") or {}
    if not isinstance(tls, dict):
        raise ConfigError("'tls' must be a mapping or null")
    tls_ca = _coerce_optional_str(tls.get("ca_certs"), "tls.ca_certs")
    tls_cert = _coerce_optional_str(tls.get("certfile"), "tls.certfile")
    tls_key = _coerce_optional_str(tls.get("keyfile"), "tls.keyfile")

    external = raw.get("external_drives") or {}
    if not isinstance(external, dict):
        raise ConfigError("'external_drives' must be a mapping")
    drives: dict[str, str] = {}
    for k, v in external.items():
        if not isinstance(k, str) or not k:
            raise ConfigError("external_drives keys must be non-empty strings")
        if not isinstance(v, str) or not v:
            raise ConfigError(
                f"external_drives[{k!r}] mount path must be a non-empty string"
            )
        drives[k] = v

    return Settings(
        mqtt_hostname=hostname,
        mqtt_port=port,
        mqtt_username=username,
        mqtt_password=password,
        client_id=client_id,
        timezone=tz,
        update_interval=update_interval,
        ha_status_topic=ha_status_topic,
        device_name=device_name,
        tls_ca_certs=tls_ca,
        tls_certfile=tls_cert,
        tls_keyfile=tls_key,
        external_drives=drives,
    )


def _settings_to_yaml_dict(s: Settings) -> dict[str, Any]:
    return {
        "mqtt": {
            "hostname": s.mqtt_hostname,
            "port": s.mqtt_port,
            "username": s.mqtt_username,
            "password": s.mqtt_password,
        },
        "client_id": s.client_id,
        "timezone": s.timezone,
        "update_interval": s.update_interval,
        "ha_status_topic": s.ha_status_topic,
        "device_name": s.device_name,
        "tls": {
            "ca_certs": s.tls_ca_certs,
            "certfile": s.tls_certfile,
            "keyfile": s.tls_keyfile,
        },
        "external_drives": dict(sorted(s.external_drives.items())),
    }


def save_settings(path: Path, settings: Settings) -> None:
    """Write YAML with a header comment. Idempotent on identical input."""
    body = (
        "# system_sensors settings.yaml\n"
        "# User-owned: edit by hand. The installer writes this file only on\n"
        "# first install and leaves it alone on subsequent re-runs.\n"
        "\n"
    )
    body += yaml.safe_dump(
        _settings_to_yaml_dict(settings),
        sort_keys=False,
        default_flow_style=False,
    )
    _atomic_write_text(path, body)


def load_sensors_enabled(path: Path) -> SensorsEnabled | None:
    """Return None if file doesn't exist. Raise ConfigError on schema violations."""
    if not path.exists():
        return None
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise ConfigError(f"Could not parse {path}: {exc}") from exc
    if raw is None:
        raise ConfigError(f"{path} is empty")
    if not isinstance(raw, dict):
        raise ConfigError(f"{path} top-level must be a mapping")

    meta = raw.get("_meta") or {}
    if not isinstance(meta, dict):
        raise ConfigError("'_meta' must be a mapping")
    last_probe_raw = meta.get("last_probe")
    if isinstance(last_probe_raw, datetime):
        last_probe = last_probe_raw
        if last_probe.tzinfo is None:
            last_probe = last_probe.replace(tzinfo=timezone.utc)
    elif isinstance(last_probe_raw, str):
        try:
            last_probe = datetime.fromisoformat(last_probe_raw.replace("Z", "+00:00"))
        except ValueError as exc:
            raise ConfigError(f"_meta.last_probe is not ISO-8601: {exc}") from exc
        if last_probe.tzinfo is None:
            last_probe = last_probe.replace(tzinfo=timezone.utc)
    else:
        last_probe = datetime.now(timezone.utc)

    sensors_raw = raw.get("sensors") or {}
    if not isinstance(sensors_raw, dict):
        raise ConfigError("'sensors' must be a mapping")
    sensors: dict[str, SensorEntry] = {}
    for name, entry in sensors_raw.items():
        if not isinstance(name, str) or not name:
            raise ConfigError("sensor keys must be non-empty strings")
        if not isinstance(entry, dict):
            raise ConfigError(f"sensors[{name!r}] must be a mapping")
        enabled = entry.get("enabled")
        available = entry.get("available")
        if not isinstance(enabled, bool):
            raise ConfigError(f"sensors[{name!r}].enabled must be a bool")
        if not isinstance(available, bool):
            raise ConfigError(f"sensors[{name!r}].available must be a bool")
        sensors[name] = SensorEntry(enabled=enabled, available=available)

    return SensorsEnabled(sensors=sensors, last_probe_utc=last_probe)


def _format_utc_iso(dt: datetime) -> str:
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    else:
        dt = dt.astimezone(timezone.utc)
    return dt.strftime("%Y-%m-%dT%H:%M:%SZ")


def save_sensors_enabled(path: Path, state: SensorsEnabled) -> None:
    """Write YAML. Sort sensors by name for stable diffs."""
    sorted_sensors = {
        name: {"enabled": entry.enabled, "available": entry.available}
        for name, entry in sorted(state.sensors.items())
    }
    body_dict: dict[str, Any] = {
        "_meta": {
            "last_probe": _format_utc_iso(state.last_probe_utc),
            "version": SENSORS_ENABLED_SCHEMA_VERSION,
        },
        "sensors": sorted_sensors,
    }
    body = (
        "# system_sensors sensors_enabled.yaml\n"
        "# Generated by system-sensors-install. User toggles in `enabled` are\n"
        "# preserved across re-probes. `available` reflects the last probe.\n"
        "\n"
    )
    body += yaml.safe_dump(body_dict, sort_keys=False, default_flow_style=False)
    _atomic_write_text(path, body)


def settings_as_dict(settings: Settings) -> dict[str, Any]:
    """Expose a Settings dataclass as a plain dict (handy for logging/testing)."""
    return asdict(settings)
